- app.py
- tests.py
Foreign key relationships and cascades are now set up in the children, mimicking the way PostgreSQL does it. I also made all foreign keys non nullable, standardized the way we use flush() vs commit() in our tests, and wrote some new tests to test the above.
> Normalizing cascading configuration, closes #164

- run_update.py
- run_update_test.py
added test verifying that missing project names are filled with github repo names
> using repo name for missing project names, closes #168

- app.py
- factories.py
- run_update_test.py
- tests.py
This feature allows the API to accept full text search queries to the endpoint `/api/projects` using query parameter `q`. It indexes `name`, `categories` and `description` fields. It also allows use to get the results only as ids by passing the `only_ids` parameter.
> [FEATURE] Search projects via full-text search

- run_update.py
- run_update_test.py
I verified that if a status column is included in a project spreadsheet it is ingested, updated, etc., and that it shows up accurately in the API output and is searchable. I also fixed a bug where values changed in the org spreadsheet weren't getting updated if the linked GitHub project hadn't been updated.
I did all this work with a [test spreadsheet](https://docs.google.com/spreadsheets/d/1a4NmpHSAR66F87u2N1zP-tmEIhcLJYmnqVD_Rk9rWtw/edit#gid=0) because I don't have edit access to any of the org spreadsheets linked from the brigade spreadsheet.
When the owners of those spreadsheets add a status column and values, they'll be reflected in the API.
also fixes #206, a bug I found while researching the problem.
> Read status column from spreadsheets

- app.py
- migrations/versions/4f685c062cff_improved_project_search.py
- test/integration/test_projects.py
Both simplifies and improves the project search process.
It simplifies by removing `github_details` from the search text. We added it to get the programming language column, but it also added a ton of junk to the search column. We've removed all of that.
It improves by adding a ranking to where the search term came from. The `status` and `tags` columns have a higher ranking than the `name` and `description` columns.
WIP until we add tests.
> WIP Improved project search

- run_update.py
Fixes issue #235 by removing trailing slashes (and whitespace) from path variable before passing to github api functions.
The github api does not appear to like endpoints which still have slashes for several calls. The urlparse function will return path's including trailing whitespace or slashes if there are no other ascii characters following them. To avoid this mismatch this patch strips the slashes and spaces before passing them to the formatting function.
> Correct Failures with Github project paths ending with slashes #235

- run_update.py
- run_update_test.py
Use the most recent of pushed_at or updated_at from GitHub details to set the project's last_updated.  
If one of these is missing it uses the other.  
If both are missing it uses current time and logs an error.  
The error is logged when the unit tests are run - is this OK?
$ python run_update_test.py 
./home/rdog/cfapi/.venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py:574: SAWarning: Unicode type received non-unicode bind param value.
processors[key](compiled_params[key])
......ERROR:run_update:GitHub Project details has neither pushed_at or updated_at, using current time.
................................
----------------------------------------------------------------------
Ran 39 tests in 30.312s
OK
> Issue 245 Use GitHub pushed_at or updated_at for Project last_updated

- app.py
- models.py
- run_update.py
Getting issues was slow because every issue was querying its project, which then queried its every issue. Then we were deleting the project's issues before we displayed it. So listing 10 issues on a project with 100 issues could generate 1,000 unneeded database calls.
I fixed this by telling the project not to request its issues, which makes the query 7-10x faster. I also made some changes for clarity along the way.
While I was researching the issue I experimented with a couple different approaches to replacing the sqlalchemy calls with raw SQL, and found that they weren't appreciably faster (less than a tenth of a second faster on average).
Closes #230 
Closes #231
> Speed up issues requests

- app.py
- test/integration/test_organizations.py
Only sends valid geojson. No more organizations without latitude or longitudes.
Closes codeforamerica/brigade#343
> Geojson tests

- run_update.py
- test/updater/test_run_update.py
The API can now handle a lower-level GitHub URL like `codeforamerica/cfapi/issues` or `codeforamerica/cfapi/wiki` passed as the code URL. It handles it by stripping anything after the project in the URL before it uses it to query the GitHub API.
Closes #261
> Handle secondary GitHub URLs

- run_update.py
- test/updater/test_run_update.py
Some Code for Philly projects were popped to the top of the list with the recent changes. This PR attempts to address that by making sure that projects with GitHub URLs that return 404s are deleted from the database, and that `.git` extensions are stripped from GitHub URLs.
> Fix zombie code for philly projects

- app.py
- test/integration/test_attendance.py
We were returning data as `text/html` from 5 routes; this fixes that and also:
- returns a non-error response from `/api/organizations/<organization_name>/attendance` when there is no attendance data available
- changes the format of what's returned from `/api/organizations/attendance` because a list isn't valid JSON
@ondrae is anything or anybody consuming the `/api/organizations/attendance` endpoint that we'd need to change or inform before we merge this PR?
Closes #279
> Fix json content headers

- Procfile
- requirements.txt
I reduced the number of gunicorn workers from 8 to 6, and upgraded gunicorn to the most recent version available via pip. This appears to've fixed the memory errors we were seeing on production.
> Improve update memory handling (part two)

- migrations/versions/4b2b7cde821f_add_org_name_to_search.py
- models.py
- test/integration/test_projects.py
Adds the `organization_name` to the search feature for projects.
Included in this PR:
Will close #260 when merged.
> Add org name to project search

- app.py
- models.py
- requirements.txt
- test/factories.py
- test/integration/test_attendance.py
- test/integration/test_organizations.py
- test/integration/test_projects.py
- test/updater/test_run_update.py
On the Brigade Project Search page, we want to show Brigade and Code for All project, but not Government projects, by default. Currently the CfAPI didn't allow you to do that. This PR changes that.
We want the default results from /projects to be the same as if you searched for http://www.codeforamerica.org/brigade/projects?type=Brigade,Code+for+All. This PR will make both of those work, at least on the CfAPI side.
Hey @tmaybe I could use your review of this. I think it could also use your work for changing how we are doing string matching, to a safer way that would prevent sql injection.
> Support searching for multiple org types at once

- README.md
- org_sources.csv
- run_update.py
- test/updater/test_run_update.py
- test_org_sources.csv
I created a new repo, [codeforamerica/brigade-information](https://github.com/codeforamerica/brigade-information) to hold organization information in JSON format, replacing the Google spreadsheet and its CSV output.
This PR updates the organization source URLs, prefers it to be in JSON format, updates relevant tests, and updates the README to reflect the new process.
Closes #293
> Read organizations from JSON

- requirements.txt
I added an extra security requirement to the requests package in `requirements.txt`. This installs extra packages to support true SSL connections as detailed in [this stackoverflow comment](http://stackoverflow.com/a/29099439/958481).
I also added `cffi` to `requirements.txt`; this prompts Heroku to install `libffi` and other security libraries. If these libraries aren't installed, the extra security requirement described above fails.
Closes #295
> Fixes requests/urllib3 InsecurePlatformWarnings

- .travis.yml
- app.py
- models.py
- requirements.txt
- templates/index.html
- test/integration/test_organizations.py
PR codeforamerica/brigade-information#42 added
"tags" information to the brigade-information repository. To help users
of this data, like myself, filter the list effectively, this commit adds
a tags query parameter to filter the list down.
For simplicity, it uses PostgreSQL's JSONB data type to store and query
the data.
> Support tag-based querying of organizations

- requirements.txt
- run_update.py
- templates/index.html
This updates the base URL we are using to fetch events for brigades to
ensure we're getting the latest events.
Previously the query had no pagination direction specified, so it
defaulted to ascending based on time. This means that groups with more
than the default page limit's worth of events would never have any
recent events.
I also updated the "page" argument in the URL to fetch the most recent
200 events. This is probably overkill, but since Meetup creates
recurring events for up to a year in advance, I wanted to make sure to
at least get the history of these events, if a brigade had up to 3
weekly recurring events. Later, we should just paginate through events
until we get some predetermined distance in the past (i.e. we stop
checking for updates to events one month after they …
> Fetch most recent meetup events for each organization

- .travis.yml
- app.py
- requirements.txt
- run_update.py
- setup.cfg
Previously, we did not have error tracking, except what was provided by
Newrelic. Unfortunately, newrelic's error offering is built more around
aggregate error rates rather than actually recording the instances of a
single error. It is hard to drill down into.
Sentry is the best-in-class error tracking/notification service. Let's
enable it for this app.
> Add Sentry (Raven) for error tracking

- migrations/versions/a5abdf9487c_add_venue_to_event.py
- models.py
- run_update.py
- test/updater/test_run_update.py
This does two things related to better surfacing event location information via the CfAPI -- fixing a bug which prevented the "location" field from ever being populated, and also adding the latitude/longitude for easier mapmaking on the client side. (Read commit messages for more detail.)
> Add location to events

- run_update.py
- test/updater/test_run_update.py
The Meetup API occasionally returns an empty response for a valid request that should return JSON. Since an empty string cannot be parsed as valid JSON, this causes an error and crashes the updating process.
I opened a support ticket about this a month ago but they don't seem to have made
any progress figuring this out.
It is very easy to reproduce by looking at the response size:
```bash
while :; do
curl -s https://api.meetup.com/2/groups\?group_urlname\=Code-for-Greenville\&key\=$MEETUP_KEY | wc -c;
done
```
which returns for me:
```
0
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
0
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
3120
0
3120
3120
```
If this method returns None, the calling method will not overwrite any
value …
> Handle empty body from Meetup API response

- requirements.txt
- test/factories.py
If simplejson is installed, Flask will autodetect it and use it for JSON
serialization. This is necessary because the lat/lon are returned from
the database as decimal objects, which are not able to be serialized by
the stdlib JSON serializer. I guess these are things you learn as you
get better at python. If I had to do it over again, I'd make the lat/lon
fields floats instead, which seems to Just Work™.
> Install simplejson for JSON serialization

- run_update.py
Some brigades have incorrect profile URLs in there.
> Handle 404 responses from GitHub when fetching org logos

- run_update.py
- test/updater/test_run_update.py
Yet another event field that wasn't being recorded: the event's
calculated end time.
I added a basic calculation. Some events don't have a defined duration,
and so Meetup recommends copying their behavior of assuming the event is
three hours long.
> Actually calculate `end_date_notz` for Events

- run_update.py
- test/updater/test_run_update.py
We've gone back and forth on this (see #245) but recently we have some
user research that shows that the "last updated at" time is generally
very out-of-sync with GitHub because there tend to be frequent updates
to a repo's metadata that are reflected in the `updated_at` timestamp
but the code remains stale as evidenced by the last commit date visible
on the repo page.
> Use `pushed_at` instead of `updated_at` for Repo update time

- app.py
- templates/index.html
- test/factories.py
This updates the notion of "upcoming" and "past" event to return events
based on their _end_ time instead of their _start_ time.
We got feedback from users that they were expecting to be able to find
the meetup they were current at (or late to) on the Brigade profile
page. To quickly meet this user need, we can just update the end time. I
assume that we are the primary user of this API and thus provides no
backwards compatibility. (Happy to add an option to this endpoint to
restore the old behavior if anyone notices this change.)
> Update "upcoming_events" to return events that haven't ended yet

- models.py
- test/factories.py
- test/integration/test_organizations.py
There was a bug where since we convert the event's start and end date
into local time for storage in the `start_time_notz` and `end_time_notz`
fields, when querying for them we were using the UTC date and time.
For example, assuming an event is scheduled for:
2018-02-07 18:30:00 PST / 2018-02-08 02:30:00 UTC
Then `start_time_notz` will be the timestamp 2018-02-07 18:30:00.
However, when filtering for "current" events, we looked for events
greater to or equal to the *UTC* time, so effectively the event would
only be returned until 2018-02-07 18:29:59 UTC (2018-02-07 10:29:59
PST).
To guard against regressions, I've adjusted the test of this data to be
much more precise. (I verified that it failed before the fix.)
This also converts the logic to use the event's end time instead, to
match …
> Fix Orgs to return events that end in the next `utc_offset` seconds

- models.py
- test/integration/test_organizations.py
- test/updater/test_run_update.py
At some point, Github added a `node_id` key in the `label` dict. This is
totally fair, it should be a backwards compatible change. However, since
we passed in the raw API response as kwargs to the Label model, this
resulted in an error.
In order to better handle this, I've updated the method signature of the
Label constructor to take an arbitrary kwargs hash and pick out the
values that are necessary.
Also, I updated the test data to prevent regressions.
Fixes #333.
> Tolerate new keys in issues' `label` dicts

- run_update.py
If a brigade is tagged with 'Code for America' and 'Brigade' we should
sync it with higher priority. This is because other organizations tend
to have a ton of repos and we deplete our GitHub API quota fetching
them.
> Prioritize syncing official CfA brigades

- run_update.py
Some events (e.g. Meetup Event id #256911740) have a venue specified
with no address. Let's handle that by just returning the location's
name.
> Handle events without a venue address
